config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :articles
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    if params[:category].blank?
      @articles = Article.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @articles = Article.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def show
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :category_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:show, :edit, :update, :destroy]

  def show
  end

  def edit
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def find_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for @article do |f| %>
  <p><%= f.input :title %></p>
  <p><%= f.input :content %></p>
  <p><%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Choisir une catégorie" } %></p>
  <p><%= f.submit %></p>
<% end %>

app/views/articles/edit.html.erb
<h1>Modifier Article</h1>

<%= render 'form' %>

<%= link_to "Retour", root_path, class: "btn btn-default"  %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <h2><%= link_to article.title, article %></h2>
  <p><%= truncate(article.content, length: 100) %></p>
  <p>Crée le: <%= article.created_at.strftime('%d %b, %y')%></p>
<% end %>

app/views/articles/new.html.erb
<h1>Nouvelle Article</h1>

  <%= render 'form' %>

  <%= link_to "Retour", root_path, class: "btn btn-default"  %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<p><%= @article.content %></p>

<div class="btn-group">
  <%= link_to "Retour", root_path, class: "btn btn-default" %>
  <% if user_signed_in? %>
    <%= link_to "Modifier", edit_article_path(@article), class: "btn btn-default" %>
    <%= link_to "Supprimer", article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default" %>
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= simple_form_for @category do |f| %>
  <p><%= f.input :name %></p>
  <p><%= f.submit %></p>
<% end %>

app/views/categories/edit.html.erb
<h1>Modifier Category</h1>

<%= render 'form' %>

<%= link_to "Retour", root_path, class: "btn btn-default"  %>

app/views/categories/new.html.erb
<h1>Nouvelle Category</h1>

<%= render 'form' %>

<%= link_to "Retour", root_path, class: "btn btn-default"  %>

app/views/categories/show.html.erb
<p><%= @category.name %></p>

<div class="btn-group">
  <%= link_to "Retour", root_path, class: "btn btn-default" %>
  <% if user_signed_in? %>
    <%= link_to "Modifier", edit_category_path(@category), class: "btn btn-default" %>
    <%= link_to "Supprimer", category_path(@category), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyWiki</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="nav navbar navbar-default navbar-fixed-top">
      <div class="container">
        <%= link_to "My Wiki", root_path, class: "navbar-bar" %>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <%= link_to "New Article", new_article_path %>
            <%= link_to "New Category", new_category_path %>
            <%= link_to "Déconnection", destroy_user_session_path, :method => :delete %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <%= yield %>
        </div>
        <div class="col-md-4">
          <ul class="list-group">
            <li><%= link_to "All Article", root_path, class: 'list-group-item' %></li>
              <% Category.all.each do |category| %>
                <li><%= link_to category.name, articles_path(category: category.name), class: 'list-group-item' %></li>
              <% end %>
          </ul>
        </div>
      </div>
    </div>
  </body>
</html>